name: Push

on:
  push:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install dependencies
        run: |
          nix develop --command bundle install

      - name: Run Scrapper
        run: |
          nix develop --command bundle exec ruby main.rb
